### ISSUE TITLE
alpine 上编译错误

### ISSUE THREAD

**Issue by windghoul** [baidu-security/openrasp-v8#8]
cmake --version
cmake version 3.13.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

g++ --version
g++ (Alpine 8.3.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

bash-4.4# gcc --version
gcc (Alpine 8.3.0) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

bash-4.4# cat /etc/alpine-release
3.9.4

问题1
xxd 没有 -i 选项

xxd --help
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: xxd [OPTIONS] [FILE]

Hex dump FILE (or stdin)

	-g N		Bytes per group
	-c N		Bytes per line
	-p		Show only hex bytes, assumes -c30
	-l LENGTH	Show only first LENGTH bytes
	-s OFFSET	Skip OFFSET bytes

经过转换后又出现编译错误。

![4501586315570_ pic_hd](https://user-images.githubusercontent.com/16053291/78740968-b063ce00-798a-11ea-960e-1dc94fd4f5f4.jpg)

请问有没有编译好的alpine 版本的包？或者在alpine 上编译的手段

**Comment by spacelan** [comment]
构建过程依赖一些静态库，目前我们没有提供apline上基于musl的静态库，所以不支持apline

**Comment by spacelan** [comment]
已支持alpine，构建流程参考：

- https://github.com/baidu-security/openrasp-v8/blob/04b8b20a7905ef044e34dde17ec49a4162f3436b/scripts/linuxmusl64.sh
- https://github.com/baidu-security/openrasp-v8/blob/04b8b20a7905ef044e34dde17ec49a4162f3436b/vendors/alpine-env/Dockerfile

**Comment by spacelan** [comment]
支持alpine:3.8及以上版本，运行时需安装依赖：

apk add libcurl libstdc++
